### ISSUE TITLE
Thomas Xin's mods (excluding The Ultimate Challenge) will NOT be supported

### ISSUE THREAD

**Issue by Leo40Git** [Leo40Git/CaveSaveEdit#5]
Rise of Ballos and Critter TD 1 have confusing profile structures (namely being split into multiple files), and Critter TD 2 will have completely hidden data files and encrypted profiles.
The Ultimate Challenge uses vanilla save files, which is why it's supported.

**Comment by 20kdc** [comment]
RoB and CTD1 can be handled by abstracting away the profile reading/writing.
CTD2... don't bother, at least not yet. Maybe when a final release comes out.

**Comment by thomas-xin** [comment]
lol don't worry
I'll make it even more difficult to edit
